# Generated by Django 5.2.3 on 2025-07-04 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0002_alter_team_created_at_alter_team_manager_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('friendly', 'Friendly'), ('competitive', 'Competitive')], max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('team_1_score', models.PositiveIntegerField(default=0)),
                ('team_2_score', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('team_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team1', to='team.team')),
                ('team_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team2', to='team.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='team.team')),
            ],
        ),
    ]
