# Generated by Django 5.2.3 on 2025-07-05 04:01

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0001_initial'),
        ('team', '0003_alter_team_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='match_type',
            new_name='mode',
        ),
        migrations.RemoveField(
            model_name='match',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='match',
            name='scheduled_at',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_1_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_2_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
        migrations.AddField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='match',
            name='scheduled_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='team_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_a', to='team.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_b', to='team.team'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ranking', models.IntegerField(default=1000)),
                ('status', models.CharField(default='available', max_length=20)),
                ('wins', models.IntegerField(default=0)),
                ('matches_played', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchmaking_owned_teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
