# Generated by Django 5.2.3 on 2025-07-07 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0002_rename_match_type_match_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('friendly', 'Friendly')], default='friendly', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='matchmaking.team')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='matchmaking.team')),
            ],
        ),
    ]
