# Generated by Django 5.2.3 on 2025-07-07 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0003_matchrequest'),
        ('team', '0003_alter_team_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchrequest',
            name='team_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='team.team'),
        ),
        migrations.AlterField(
            model_name='matchrequest',
            name='team_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='team.team'),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
